# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import server_pb2 as server__pb2


class RMServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QueryWorker = channel.unary_unary(
                '/RMServer/QueryWorker',
                request_serializer=server__pb2.IntVal.SerializeToString,
                response_deserializer=server__pb2.BooleanResponse.FromString,
                )


class RMServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def QueryWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RMServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QueryWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryWorker,
                    request_deserializer=server__pb2.IntVal.FromString,
                    response_serializer=server__pb2.BooleanResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RMServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RMServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def QueryWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RMServer/QueryWorker',
            server__pb2.IntVal.SerializeToString,
            server__pb2.BooleanResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
