# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='server.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cserver.proto\"\x17\n\x06IntVal\x12\r\n\x05value\x18\x01 \x01(\x05\" \n\x0f\x42ooleanResponse\x12\r\n\x05value\x18\x01 \x01(\x08\x32\x36\n\x08RMServer\x12*\n\x0bQueryWorker\x12\x07.IntVal\x1a\x10.BooleanResponse\"\x00\x62\x06proto3'
)




_INTVAL = _descriptor.Descriptor(
  name='IntVal',
  full_name='IntVal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='IntVal.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=39,
)


_BOOLEANRESPONSE = _descriptor.Descriptor(
  name='BooleanResponse',
  full_name='BooleanResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='BooleanResponse.value', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=73,
)

DESCRIPTOR.message_types_by_name['IntVal'] = _INTVAL
DESCRIPTOR.message_types_by_name['BooleanResponse'] = _BOOLEANRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IntVal = _reflection.GeneratedProtocolMessageType('IntVal', (_message.Message,), {
  'DESCRIPTOR' : _INTVAL,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:IntVal)
  })
_sym_db.RegisterMessage(IntVal)

BooleanResponse = _reflection.GeneratedProtocolMessageType('BooleanResponse', (_message.Message,), {
  'DESCRIPTOR' : _BOOLEANRESPONSE,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:BooleanResponse)
  })
_sym_db.RegisterMessage(BooleanResponse)



_RMSERVER = _descriptor.ServiceDescriptor(
  name='RMServer',
  full_name='RMServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=75,
  serialized_end=129,
  methods=[
  _descriptor.MethodDescriptor(
    name='QueryWorker',
    full_name='RMServer.QueryWorker',
    index=0,
    containing_service=None,
    input_type=_INTVAL,
    output_type=_BOOLEANRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RMSERVER)

DESCRIPTOR.services_by_name['RMServer'] = _RMSERVER

# @@protoc_insertion_point(module_scope)
